id: P2AEF247F
initial_creation_type: input
source_metadata:
  title: Buddha Śākyamuni Prayers & Practices
  language: it
  description: 'Lotsawa House presents the following texts as part of its Prayers
    to Buddha Śākyamuni Series:'
  volume:
    d0033d5b3431410491d67c787be50af5:
      title: Prayer for the Future of the Dharma
      parent: Aspiration Prayers
    37e029e548bc432dbc45fb6db44915b6:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Aspiration Prayers
    56f103466b694f5bb40d2a693101a319:
      title: 'The Sage''s Powerful Words of Truth: A Prayer for the Spread of the
        Omniscient Buddha''s Teachings'
      parent: Aspiration Prayers
    449a5690e0c14b1d884113b76a01b532:
      title: Verses on the Buddha's Previous Lives
      parent: History
    0f5a001e80a4423da5d50fad7b63e3df:
      title: Short Praise of the Buddha's Deeds
      parent: Buddha's Deeds
    017efac7213b4f4bb7d838b080258d09:
      title: Praise of the Twelve Acts of the Buddha
      parent: Buddha's Deeds
    6501381e808140c38d22fd2aa876d21f:
      title: 'Praise of the Buddha: With Skilful Means & Compassion...'
      parent: Buddha's Deeds
    2c05058286b74015b0f76862c7636eeb:
      title: Verses of Homage to the Buddhas and Bodhisattvas Together with their
        Mantras
      parent: Praise
    4e9aec874c5249e3963989e494c7ab3d:
      title: A Brief Practice of Paying Homage and Making Offerings to the Sixteen
        Elders
      parent: Sādhanas
    c6bf36e1e888434fb2120103a0397cff:
      title: 'The Heart of Wish-Fulfilling Jewels: A Brief Practice for Paying Homage
        and Making Offerings to the Buddha together with his retinue of Arhats'
      parent: Sādhanas
    6b93c1589b3a498786f1a813318c35e5:
      title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
      parent: Sādhanas
    554767feb04e4d479cb33c35aaea4820:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Sādhanas
    cc88f92b990a4247be93199beb9696dd:
      title: 'The Sage who Dispels Mind’s Anguish: Advice from the Guru, the Gentle
        Protector Mañjuśrī on the Means of Accomplishing the Yogas of Śamatha and
        Vipaśyanā'
      parent: Commentaries
created_at: '2022-03-01T03:05:43.226304'
last_modified_at: '2022-03-01T03:05:43.226307'
